### ISSUE TITLE
ToDo List

### ISSUE THREAD

**Issue by cleberpereiradasilva** [cleberpereiradasilva/java-back-end-users#1]
- [x] First Start with *How to run* in **README.md**
- [x] Create model **User**
- [x] Create CRUD to **User**
- [x] Create **RequestUserDTO**
- [x] Create **ResponsetUserDTO**
- [x] Create First Test
- [x] Create Test for **User**
